### ISSUE TITLE
Clean links

### ISSUE THREAD

**Issue by FatOrangutan** [MarkaPola/Linkificator#1]
I am trying to include the functionality of Clean Links addon (https://addons.mozilla.org/en-us/firefox/addon/clean-links/) in this addon since I don't like the idea of two addons scanning through all the links in every page.
I had two questions:
1. Is this possible, using the Custom Rules?
2. If yes, can you give me an example of what to enter in the Pattern and URL fields?

Thanks.

**Comment by MarkaPola** [comment]
Linkificator and 'Clean Links' do not work on the same elements of HTML documents.
Linkificator does not process anchor tags (&lt;a&gt;) so adding a custom rule will not help because this rule will never be applied to &lt;a&gt; elements.
The solution seems to install both extensions and ensure 'Clean Links' is configured in delegation mode (default). So Linkificator will transform all URLs in anchors and, by clicking on these links, 'Clean Links' will clean-up, if needed, the URL.
