### ISSUE TITLE
[Feature Request] Open link in new tab

### ISSUE THREAD

**Issue by gluons** [MarkaPola/Linkificator#14]
It should have an option to make link as `_blank` link. So, I can clink link to open in new tab.

**Comment by MarkaPola** [comment]
Firefox supports natively to open links in a new tab: use the middle button of your mouse rather than the left one or "Command-click" on MacOS with magic mouse.

If you have trouble to get it working check that config "browser.tabs.opentabfor.middleclick" is set to true (type "about:config" in your url bar and after "middle" in the search bar).

So This feature will never implemented in Linkificator.

**Comment by gluons** [comment]
OK. Fine.  
Just a feature request for my laziness.
