### ISSUE TITLE
Text rubbish at end of Linkificator string/link

### ISSUE THREAD

**Issue by zutroi67** [MarkaPola/Linkificator#18]
Text from an HTML "preformatted text" structure from a well-known video website.

Raw source code of text URLs:

[img]https://lookpic.com/cdn/i2/440/Uiexp7eb.png[/img]
[img]https://lookpic.com/cdn/i2/384/L1pH5RDL.png[/img]
[img]https://lookpic.com/cdn/i2/429/5H3kie7I.png[/img]

After Linkificating, the resulting clickable URL turns to:

https://lookpic.com/cdn/i2/429/5H3kie7I.png[/img] instead of
https://lookpic.com/cdn/i2/429/5H3kie7I.png

The trailing rubbish "[/png]" needs to be stripped off.

**Environment:**
Processor	Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.21 GHz
Installed RAM	16.0 GB (15.9 GB usable)
System type	64-bit operating system, x64-based processor

Firefox 110.0 (64-bit)

Linkificator 3.3.3

Thanks for the addon. It's great!

**Comment by MarkaPola** [comment]
Because  the trailing `[/img]` is a perfect valid sequence of characters as part of an URL, it is not possible to ignore this as part of the standard process of linkification.

However, you can use custom rules to achieve what you want. I suggest you to create a custom rule in the category `Befor predefined rules` in `Custom Rules` tab with the following values:
* Name: IMG (or any text identifying the rule)
* Pattern: \[img](.+)\[/img]
* URL: $1

And don't forget to activate custom rules of the category `Apply Custom Rules for: Before predefined rules list` specified in `Links` tab.
