### ISSUE TITLE
Linkify and open only on doubleclick

### ISSUE THREAD

**Issue by ionelmc** [MarkaPola/Linkificator#8]
The old extension had such a feature, is it possible with the new API?

**Comment by MarkaPola** [comment]
Linkificator never had this feature (may be you confuse with Linkification which is a completely different add-on).

For now, I have no plan to add this feature because I find this behavior unnatural and another add-on already offers it ([text-link](https://addons.mozilla.org/en-US/firefox/addon/text-link/)).
